## Pandas

Tabular data with **pandas** (pandas 2.x).

Reference: https://pandas.pydata.org/docs/

In [1]:
import datetime
print(datetime.datetime.now())

2026-05-21 13:40:16.189203

In [2]:
import numpy as np
import pandas as pd

pd.__version__

'2.3.3'

### Series

A **Series** is a one-dimensional labeled array: values plus an **index** (row labels).

In [3]:
ser = pd.Series([1, 3, 5, 7])
print(type(ser))
ser

<class 'pandas.core.series.Series'>

0    1
1    3
2    5
3    7
dtype: int64

In [4]:
ser.values   # NumPy array of values
ser.index    # index labels (default: 0, 1, 2, ...)

RangeIndex(start=0, stop=4, step=1)

In [5]:
ser2 = pd.Series([1, 3, 5, 7], index=["d", "b", "c", "a"])
ser2

d    1
b    3
c    5
a    7
dtype: int64

In [6]:
# Label-based selection (index labels, not positions)
ser2["a"]
ser2[["a", "b", "d"]]

a    7
b    3
d    1
dtype: int64

In [7]:
# Boolean filtering
ser2[ser2 > 4]

c    5
a    7
dtype: int64

In [8]:
# Vectorized arithmetic (aligned by index)
ser2 * 2
np.exp(ser2)

d       2.718282
b      20.085537
c     148.413159
a    1096.633158
dtype: float64

In [9]:
# Membership tests the *index*, not the values
"b" in ser2

True

Build a Series from a Python `dict`. Missing index labels become `NaN`.

In [10]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
ser3 = pd.Series(sdata)
ser3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [11]:
states = ["California", "Ohio", "Oregon", "Texas"]
ser4 = pd.Series(sdata, index=states)
ser4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [12]:
# Missing values: prefer isna / notna (isnull / notnull are aliases)
ser4.isna()
ser4.notna()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [13]:
# Arithmetic aligns on the index; non-overlapping labels become NaN
ser3 + ser4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [14]:
ser4.name = "population"
ser4.index.name = "states"
ser4

states
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

### DataFrame

A **DataFrame** is a table: rows and columns, each axis has an index. Think of it as a dict of Series sharing the same row index.

In [15]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9],
}
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [16]:
df = pd.DataFrame(data, columns=["year", "state", "pop"])
df

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [17]:
df2 = pd.DataFrame(
    data,
    columns=["year", "state", "pop", "debt"],
    index=["one", "two", "three", "four", "five"],
)
df2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [18]:
# Column access: attribute or brackets (brackets required if name has spaces)
df2["year"]
df2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

### `loc` and `iloc`

- **`loc`**: label-based (row/column names)
- **`iloc`**: integer position-based (0-based)

Prefer `df.loc[row, col]` over chained indexing such as `df[col][row]`.

In [19]:
df2.loc["two"]          # one row (Series)
df2.loc["two", "pop"]     # one scalar
df2.loc["two":"four", ["year", "pop"]]

       year  pop
two    2001  1.7
three  2002  3.6
four   2001  2.4

In [20]:
df2.iloc[1]             # second row
df2.iloc[1:3, [0, 2]]     # rows 1–2, columns 0 and 2

       year  pop
two    2001  1.7
three  2002  3.6

In [21]:
df2["debt"] = 5.0
df2

       year   state  pop  debt
one    2000    Ohio  1.5   5.0
two    2001    Ohio  1.7   5.0
three  2002    Ohio  3.6   5.0
four   2001  Nevada  2.4   5.0
five   2002  Nevada  2.9   5.0

In [22]:
# Assign a Series aligned on the index (non-matching rows become NaN)
ser = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
df2["debt"] = ser
df2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [23]:
df2["eastern"] = df2["state"] == "Ohio"
df2

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [24]:
df2.T  # transpose

          one   two three    four    five
year     2000  2001  2002    2001    2002
state    Ohio  Ohio  Ohio  Nevada  Nevada
pop       1.5   1.7   3.6     2.4     2.9
debt      NaN  -1.2   NaN    -1.5    -1.7
eastern  True  True  True   False   False

In [25]:
# Index objects are immutable
df2.index
try:
    df2.index[0] = "oneone"
except TypeError as e:
    print(e)

Index does not support mutable operations

### Reindexing

`reindex` returns a **new** object with labels rearranged, added, or removed. Missing entries are `NaN` unless you fill them.

In [26]:
ser1 = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
ser2 = ser1.reindex(["a", "b", "c", "d", "e"])
ser2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [27]:
ser1.reindex(["a", "b", "c", "d", "e"], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [28]:
# Ordered categories / time series: forward-fill after reindex
ser3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
ser4 = ser3.reindex(range(6)).ffill()
ser3, ser4

(0      blue
 2    purple
 4    yellow
 dtype: object,
 0      blue
 1      blue
 2    purple
 3    purple
 4    yellow
 5    yellow
 dtype: object)

### Selecting and transforming rows/columns

In [29]:
data = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"],
)
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [30]:
data.drop(["Colorado", "Ohio"])  # drop rows (returns new DataFrame)

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [31]:
data.drop(columns=["two", "four"])  # prefer columns= over axis=1

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [32]:
data.iloc[:2]  # first two rows by position

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [33]:
data[data["three"] > 5]  # boolean row filter

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [34]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [35]:
# Arithmetic is aligned on both axes
data + data.iloc[::-1]

          one  two  three  four
Colorado    8   10     12    14
New York   24   26     28    30
Ohio        0    2      4     6
Utah       16   18     20    22

### `apply` and sorting

In [36]:
rng = np.random.default_rng(0)
frame = pd.DataFrame(
    rng.standard_normal((4, 3)),
    index=["Utah", "Ohio", "Texas", "Oregon"],
    columns=list("abd"),
)
frame

               a         b         d
Utah    0.125730 -0.132105  0.640423
Ohio    0.104900 -0.535669  0.361595
Texas   1.304000  0.947081 -0.703735
Oregon -1.265421 -0.623274  0.041326

In [37]:
# apply: column-wise (axis=0) or row-wise (axis=1)
frame.apply(lambda col: col.max() - col.min(), axis=0)

a    2.569422
b    1.570355
d    1.344158
dtype: float64

In [38]:
# Element-wise transforms on a DataFrame use .map() (formerly applymap)
frame.map(lambda x: round(x, 2))

           a     b     d
Utah    0.13 -0.13  0.64
Ohio    0.10 -0.54  0.36
Texas   1.30  0.95 -0.70
Oregon -1.27 -0.62  0.04

In [39]:
frame.sort_index()  # sort rows by index
frame.sort_index(axis=1, ascending=False)

               d         b         a
Utah    0.640423 -0.132105  0.125730
Ohio    0.361595 -0.535669  0.104900
Texas  -0.703735  0.947081  1.304000
Oregon  0.041326 -0.623274 -1.265421

### Summarizing and descriptive statistics

In [40]:
df = pd.DataFrame(
    [[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
    index=["a", "b", "c", "d"],
    columns=["one", "two"],
)
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [41]:
df.sum()
df.sum(axis=1)
df.mean(axis=1, skipna=False)
df.cumsum()
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [42]:
s = pd.Series(["a", "a", "b", "c"] * 4)
s.describe()  # includes count, unique, top, freq for object dtype

count     16
unique     3
top        a
freq       8
dtype: object

### Sample price panel (pandas + NumPy)

Build a small **synthetic** daily panel of closing prices and volume—no extra packages or network. Same pandas workflows apply to real CSV/API data later.

In [43]:
rng = np.random.default_rng(42)
dates = pd.bdate_range("2024-01-01", periods=60)
companies = ["AAPL", "IBM", "MSFT", "GOOG"]

# Simulated closing prices (geometric random walk)
close = pd.DataFrame(
    {
        sym: 100 * np.exp(np.cumsum(rng.standard_normal(len(dates)) * 0.012))
        for sym in companies
    },
    index=dates,
)
volume = pd.DataFrame(
    {sym: rng.integers(1_000_000, 8_000_000, size=len(dates)) for sym in companies},
    index=dates,
)
close.head()

                  AAPL        IBM        MSFT        GOOG
2024-01-01  100.366330  98.000810   98.779315  101.579547
2024-01-02   99.121561  97.607773   98.992048  101.847317
2024-01-03  100.018223  97.798591   99.253728  101.346331
2024-01-04  101.153501  98.488997  100.885856  102.700721
2024-01-05   98.812760  99.333170  101.901949  103.230486

### Correlation and covariance

In [44]:
volume.head()

               AAPL      IBM     MSFT     GOOG
2024-01-01  1832260  6152093  2748590  5065537
2024-01-02  3619288  7125034  2865243  1591452
2024-01-03  7485305  6548558  1427932  4662592
2024-01-04  3981174  6957921  1978378  7551578
2024-01-05  1796101  4755595  4035330  6063915

In [45]:
# Daily percent change (returns); first row is NaN
ptc_close = close.pct_change()
ptc_close.tail()

                AAPL       IBM      MSFT      GOOG
2024-03-18 -0.007637 -0.006334  0.002073 -0.007819
2024-03-19 -0.003296  0.002796  0.019130 -0.025438
2024-03-20  0.018101  0.000262  0.001922 -0.001950
2024-03-21 -0.010336  0.019407 -0.001423 -0.012668
2024-03-22  0.011687 -0.002868  0.003436 -0.006333

In [46]:
ptc_close["AAPL"].corr(ptc_close["IBM"])
pd.Series.corr(ptc_close["AAPL"], ptc_close["IBM"])

np.float64(-0.06349342380763556)

In [47]:
ptc_close["AAPL"].cov(ptc_close["IBM"])
ptc_close.corr()
ptc_close.cov()

          AAPL       IBM      MSFT      GOOG
AAPL  0.000090 -0.000005  0.000002  0.000008
IBM  -0.000005  0.000081  0.000003 -0.000025
MSFT  0.000002  0.000003  0.000151  0.000027
GOOG  0.000008 -0.000025  0.000027  0.000143

In [48]:
ptc_close.corrwith(ptc_close["IBM"])
ptc_close.corrwith(volume)  # matching column names

AAPL   -0.034255
IBM     0.044494
MSFT   -0.273801
GOOG   -0.015082
dtype: float64

### Value counts

In [49]:
df = pd.DataFrame(
    {"Qu1": [1, 3, 4, 3, 4], "Qu2": [2, 3, 1, 2, 3], "Qu3": [1, 5, 2, 4, 4]}
)
df

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [50]:
# Per-column value counts stacked into one table
df.apply(pd.Series.value_counts).fillna(0).astype(int)

   Qu1  Qu2  Qu3
1    1    1    1
2    0    2    1
3    2    2    0
4    2    0    2
5    0    0    1

### Handling missing data

In [51]:
s_data = pd.Series(["aardvark", "artichoke", np.nan, "avocado"])
s_data.isna()
s_data.dropna()
s_data.fillna("N/A")

0     aardvark
1    artichoke
2          N/A
3      avocado
dtype: object

In [52]:
rng = np.random.default_rng(1)
s = pd.Series(rng.standard_normal(21))
s = s.mask(s < 0)  # preferred over s[s < 0] = np.nan for clarity
df = pd.DataFrame(s.to_numpy().reshape(7, 3))
df

          0         1         2
0  0.345584  0.821618  0.330437
1       NaN  0.905356  0.446375
2       NaN  0.581118  0.364572
3  0.294132  0.028422  0.546713
4       NaN       NaN       NaN
5  0.598846  0.039722       NaN
6       NaN       NaN  0.008142

In [53]:
rng = np.random.default_rng(2)
df = pd.DataFrame(rng.standard_normal((7, 3)))
df = df.where(df > 0)  # keep positives; others become NaN
df

          0         1         2
0  0.189053       NaN       NaN
1       NaN  1.799707  1.144166
2       NaN  0.773807  0.281211
3       NaN  0.977567       NaN
4       NaN       NaN  0.454958
5       NaN  0.545289       NaN
6  0.126828       NaN  0.841465

In [54]:
df.fillna({0: -0.5, 1: -1})
df.ffill()  # forward-fill (replaces fillna(method='ffill'))

          0         1         2
0  0.189053       NaN       NaN
1  0.189053  1.799707  1.144166
2  0.189053  0.773807  0.281211
3  0.189053  0.977567  0.281211
4  0.189053  0.977567  0.454958
5  0.189053  0.545289  0.454958
6  0.126828  0.545289  0.841465

In [55]:
df.mean()
df.fillna(df.mean())

          0         1         2
0  0.189053  1.024093  0.680450
1  0.157941  1.799707  1.144166
2  0.157941  0.773807  0.281211
3  0.157941  0.977567  0.680450
4  0.157941  1.024093  0.454958
5  0.157941  0.545289  0.680450
6  0.126828  1.024093  0.841465

### Hierarchical (MultiIndex)

In [56]:
rng = np.random.default_rng(3)
data = pd.Series(
    rng.standard_normal(10),
    index=[
        ["a", "a", "a", "b", "b", "b", "c", "c", "d", "d"],
        [1, 2, 3, 1, 2, 3, 1, 2, 2, 3],
    ],
)
data
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [57]:
data["b"]       # all rows whose outer label is 'b'
data["b":"c"]     # slice on the outer level

b  1   -0.567770
   2   -0.452649
   3   -0.215597
c  1   -2.019986
   2   -0.231932
dtype: float64

In [58]:
data.loc[:, 2]  # all outer labels, inner level == 2

a   -2.555665
b   -0.452649
c   -0.231932
d   -0.865213
dtype: float64

In [59]:
data.unstack()       # Series -> DataFrame (inner index becomes columns)
data.unstack().stack()  # back to Series; NaN where no value existed

a  1    2.040919
   2   -2.555665
   3    0.418099
b  1   -0.567770
   2   -0.452649
   3   -0.215597
c  1   -2.019986
   2   -0.231932
d  2   -0.865213
   3    3.323000
dtype: float64

In [60]:
frame = pd.DataFrame(
    np.arange(12).reshape((4, 3)),
    index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
    columns=[["Ohio", "Ohio", "Colorado"], ["Green", "Red", "Green"]],
)
frame.index.names = ["key1", "key2"]
frame.columns.names = ["state", "color"]
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [61]:
frame.swaplevel("key1", "key2")
frame.sum()

state     color
Ohio      Green    18
          Red      22
Colorado  Green    26
dtype: int64

### `set_index` and `reset_index`

In [62]:
frame = pd.DataFrame(
    {
        "a": range(7),
        "b": range(7, 0, -1),
        "c": ["one", "one", "one", "two", "two", "two", "two"],
        "d": [0, 1, 2, 0, 1, 2, 3],
    }
)
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [63]:
frame.set_index(["c", "d"], drop=True)  # try drop=False to keep columns

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [64]:
frame.set_index(["c", "d"]).reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1